apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: self-signed
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.certManager.namespace }}
  syncPolicy:
    automated:
      selfHeal: true

  source:
    repoURL: https://github.com/mazelab/argocd-root-basics.git
    path: charts/my-selfsigned-ca
    targetRevision: {{ .Values.branch }}
    helm:
      valuesObject:
        namespace: {{ .Values.certManager.namespace }}
        certManager:
          clusterIssuer: {{ .Values.certManager.clusterIssuer }}

